version: '3.8'

services:
  transcription-api:
    image: transcricao-node
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_swarm_public"
        - "traefik.http.routers.transcription-api.rule=Host(`api-transcricao.mlgrupo.com.br`)"
        - "traefik.http.routers.transcription-api.entrypoints=websecure"
        - "traefik.http.routers.transcription-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.transcription-api.loadbalancer.server.port=9898"
    environment:
      - NODE_ENV=production
      - PORT=9898
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/transcricao-whisper-v1/credentials.json:/app/credentials.json:ro
      - /opt/transcricao-whisper-v1/token.json:/app/token.json:rw
      - /opt/transcricao-whisper-v1/temp:/app/temp:rw


networks:
  network_swarm_public:
    external: true
